import type { Locale } from "./locales";

const zh = {
  a11y: { breadcrumb: "面包屑导航" },
  header: { siteLink: "Agent Mentor 官网 ↗", switcher: "切换语言" },
  drill: {
    glossaryMore: "复制术语给 Agent →",
    deeper: "再深一层",
    liveBadge: "未过质检",
    copied: "已复制",
    copyFail: "复制失败",
  },
  reader: {
    breadcrumbCourses: "课程",
    library: {
      title: "把正在发生的 Agent 变化，讲成能立刻上手的课。",
      intro: "这里只收录与 Agent 直接相关、仍在快速变化的选题。课程免费阅读，练习、代码和选中文本都能一键复制给 Claude Code、Codex 或其他 Agent 继续做。",
      emptyTitle: "首门课程正在生成",
      emptyBody: "课程必须通过来源、互动与 Agent 相关性检查后才会出现在这里。",
      ctaTitle: "想让 Agent 为你的目标定制一门课？",
      ctaBody: "Agent Mentor 把课程、练习与来源保存到本地，交给你自己的 Agent 使用。",
      ctaButton: "了解 Agent Mentor ↗",
      courseCount: (n: number) => `${n} 门课`,
    },
    course: {
      start: "开始学习",
      glossary: "术语表",
      sources: "来源",
      ctaTitle: "想学自己的主题？",
      ctaBody: "Agent Mentor 会在你的本机生成带来源、练习和互动的课程。",
      ctaButton: "了解 Agent Mentor ↗",
    },
    glossary: {
      breadcrumbSelf: "术语表",
      title: "术语表",
      subtitle: (n: number, courseTitle: string) => `${n} 个术语，来自《${courseTitle}》。正文首次出现时可悬停查看释义。`,
      thTerm: "术语",
      thDef: "释义",
      thSource: "来源",
    },
    sources: { breadcrumbSelf: "来源" },
    card: {
      lessons: (n: number) => `${n} 节`,
      minutes: (n: number) => `约 ${n} 分钟`,
    },
    courseNav: { toc: "课时" },
    lessonNav: { prev: "上一节", next: "下一节" },
    copy: {
      code: "复制代码",
      copied: "已复制",
      failed: "复制失败",
      link: "复制本节链接",
    },
  },
  blocks: {
    common: {
      check: "检查",
      reset: "重置",
      showFeedback: "查看反馈",
      copyToAgent: "复制给 Agent",
      localCheckPassed: "本地检查通过。",
      localCheckFailed: "本地检查未通过。",
      loadingEditor: "加载编辑器…",
    },
    exercise: {
      heading: "练习",
      title: (n: number, level: string) => `练习 ${n} · ${level}`,
      untitled: (n: number) => `练习 ${n}`,
      hint: (n: number) => `提示 ${n}`,
      showAnswer: "看参考答案",
      rubric: "完成标准 · 本地勾选",
      agentCopy: { aria: "复制这道练习给 Agent", idle: "复制练习给 Agent" },
    },
    mentorAction: {
      kicker: "Agent 动作",
      landmark: (label: string) => `Agent 动作：${label}`,
      copyAria: (label: string) => `复制给 Agent：${label}`,
    },
    order: {
      dragAria: (text: string) => `拖动排序：${text}`,
      moveUpAria: (text: string) => `上移：${text}`,
      moveDownAria: (text: string) => `下移：${text}`,
    },
    predict: { myPrediction: "我的预测" },
    trace: {
      stepColumn: "步骤",
      cellPassed: "通过",
      cellRetry: "再看",
      allFilled: "可填写格子全通过。",
      partialFilled: (passed: number, total: number) => `可填写格子 ${passed}/${total} 通过。`,
    },
    code: {
      slotAria: (n: number) => `代码空位 ${n}`,
      bugLabel: "坏掉的现象：",
      editorAria: "代码输入",
      allPassed: "本地检查全通过。",
      partialPassed: (passed: number, total: number) => `本地检查 ${passed}/${total} 通过。`,
    },
    diff: { choicesAria: "改动解释选项" },
    sandbox: {
      preview: "预览",
      restoreMine: "恢复我的代码",
      showAnswer: "看参考答案",
      inspect: "检查",
      console: "控制台",
      noMessages: "无消息",
      clear: "清空",
      replPlaceholder: "输入表达式，回车执行",
      replAria: "控制台输入",
      tabChangedAria: "参考答案改动了此段",
      closeErrorAria: "关闭错误提示",
      mine: "我的",
      answer: "答案",
      myCodePreviewTitle: "我的代码预览",
      currentCodeLabel: "当前代码：",
      emptyFile: "（空）",
      fileListSeparator: "、",
      statusRunning: "运行中…",
      statusErrors: (n: number) => `${n} 个错误`,
      statusAchieved: "目标达成",
      statusOk: "已运行 · 无错误",
      editorAria: (tabLabel: string) => `${tabLabel} 编辑器`,
      toastAchieved: "目标达成。可以复制给 Agent 继续讨论你的解法。",
      toastLoadedShared: "已加载分享的代码",
      toastRestoredAttempt: "已恢复你上次的尝试，重置可回到初始状态",
      toastAppliedSolution: (files: string[]) => `已应用参考答案，改动在 ${files.join("、")}。`,
      toastSolutionMatches: "参考答案与你的当前代码一致。",
      toastRestoredBeforeAnswer: "已恢复查看答案前的代码。",
    },
  },
};

export type SiteCopy = typeof zh;

const en: SiteCopy = {
  a11y: { breadcrumb: "Breadcrumb" },
  header: { siteLink: "Agent Mentor ↗", switcher: "Switch language" },
  drill: {
    glossaryMore: "Copy term to Agent →",
    deeper: "One level deeper",
    liveBadge: "not course-checked",
    copied: "Copied",
    copyFail: "Copy failed",
  },
  reader: {
    breadcrumbCourses: "Courses",
    library: {
      title: "Agent changes, turned into courses you can use right away.",
      intro: "Only topics that are directly about Agents and still moving fast. Courses are free; exercises, code, and selected text copy straight into Claude Code, Codex, or your Agent of choice.",
      emptyTitle: "The first course is being generated",
      emptyBody: "Courses appear here only after passing source, interaction, and Agent-relevance checks.",
      ctaTitle: "Want a course built around your own goal?",
      ctaBody: "Agent Mentor saves courses, exercises, and sources locally, ready for your own Agent.",
      ctaButton: "Explore Agent Mentor ↗",
      courseCount: (n: number) => `${n} ${n === 1 ? "course" : "courses"}`,
    },
    course: {
      start: "Start course",
      glossary: "Glossary",
      sources: "Sources",
      ctaTitle: "Want a course for your own goal?",
      ctaBody: "Agent Mentor generates sourced, interactive courses on your machine.",
      ctaButton: "Explore Agent Mentor ↗",
    },
    glossary: {
      breadcrumbSelf: "Glossary",
      title: "Glossary",
      subtitle: (n: number, courseTitle: string) => `${n} ${n === 1 ? "term" : "terms"} from “${courseTitle}.” Hover the first occurrence in the lesson for its definition.`,
      thTerm: "Term",
      thDef: "Definition",
      thSource: "Source",
    },
    sources: { breadcrumbSelf: "Sources" },
    card: {
      lessons: (n: number) => `${n} ${n === 1 ? "lesson" : "lessons"}`,
      minutes: (n: number) => `~${n} min`,
    },
    courseNav: { toc: "Lessons" },
    lessonNav: { prev: "Previous", next: "Next" },
    copy: {
      code: "Copy code",
      copied: "Copied",
      failed: "Copy failed",
      link: "Copy section link",
    },
  },
  blocks: {
    common: {
      check: "Check",
      reset: "Reset",
      showFeedback: "Show feedback",
      copyToAgent: "Copy to Agent",
      localCheckPassed: "Local check passed.",
      localCheckFailed: "Local check failed.",
      loadingEditor: "Loading editor…",
    },
    exercise: {
      heading: "Exercises",
      title: (n: number, level: string) => `Exercise ${n} · ${level}`,
      untitled: (n: number) => `Exercise ${n}`,
      hint: (n: number) => `Hint ${n}`,
      showAnswer: "Show reference answer",
      rubric: "Done criteria · checked locally",
      agentCopy: { aria: "Copy this exercise to Agent", idle: "Copy exercise to Agent" },
    },
    mentorAction: {
      kicker: "Agent action",
      landmark: (label: string) => `Agent action: ${label}`,
      copyAria: (label: string) => `Copy to Agent: ${label}`,
    },
    order: {
      dragAria: (text: string) => `Drag to reorder: ${text}`,
      moveUpAria: (text: string) => `Move up: ${text}`,
      moveDownAria: (text: string) => `Move down: ${text}`,
    },
    predict: { myPrediction: "My prediction" },
    trace: {
      stepColumn: "Step",
      cellPassed: "Passed",
      cellRetry: "Retry",
      allFilled: "All fillable cells passed.",
      partialFilled: (passed: number, total: number) => `${passed}/${total} fillable ${total === 1 ? "cell" : "cells"} passed.`,
    },
    code: {
      slotAria: (n: number) => `Code slot ${n}`,
      bugLabel: "What's broken:",
      editorAria: "Code input",
      allPassed: "Local check: all passed.",
      partialPassed: (passed: number, total: number) => `Local check: ${passed}/${total} passed.`,
    },
    diff: { choicesAria: "Explanations for this change" },
    sandbox: {
      preview: "Preview",
      restoreMine: "Restore my code",
      showAnswer: "Show reference answer",
      inspect: "Inspect",
      console: "Console",
      noMessages: "No messages",
      clear: "Clear",
      replPlaceholder: "Type an expression, press Enter to run",
      replAria: "Console input",
      tabChangedAria: "The reference solution changed this file",
      closeErrorAria: "Close error message",
      mine: "Mine",
      answer: "Answer",
      myCodePreviewTitle: "My code preview",
      currentCodeLabel: "Current code:",
      emptyFile: "(empty)",
      fileListSeparator: ", ",
      statusRunning: "Running…",
      statusErrors: (n: number) => `${n} ${n === 1 ? "error" : "errors"}`,
      statusAchieved: "Goal reached",
      statusOk: "Ran · no errors",
      editorAria: (tabLabel: string) => `${tabLabel} editor`,
      toastAchieved: "Goal reached. Copy to Agent to continue with your solution.",
      toastLoadedShared: "Loaded shared code",
      toastRestoredAttempt: "Restored your last attempt; reset returns to the original",
      toastAppliedSolution: (files: string[]) => `Applied the reference solution in ${files.join(", ")}.`,
      toastSolutionMatches: "The reference solution matches your current code.",
      toastRestoredBeforeAnswer: "Restored the code from before you viewed the answer.",
    },
  },
};

const ja: SiteCopy = {
  a11y: { breadcrumb: "パンくずリスト" },
  header: { siteLink: "Agent Mentor 公式サイト ↗", switcher: "言語を切り替え" },
  drill: {
    glossaryMore: "用語を Agent にコピー →",
    deeper: "もう一段深く",
    liveBadge: "品質チェック未通過",
    copied: "コピーしました",
    copyFail: "コピーに失敗しました",
  },
  reader: {
    breadcrumbCourses: "コース",
    library: {
      title: "いま起きている Agent の変化を、すぐ使えるレッスンに。",
      intro: "Agent に直接関係し、いまも急速に変化しているテーマだけを収録しています。コースはすべて無料。練習・コード・選択したテキストはワンクリックで Claude Code、Codex などの Agent にコピーして続けられます。",
      emptyTitle: "最初のコースを生成中です",
      emptyBody: "出典・インタラクション・Agent 関連性のチェックを通過したコースだけがここに表示されます。",
      ctaTitle: "自分の目標に合わせたコースを Agent に作ってもらいたい方へ",
      ctaBody: "Agent Mentor はコース・練習・出典をローカルに保存し、あなた自身の Agent に渡せます。",
      ctaButton: "Agent Mentor を見る ↗",
      courseCount: (n: number) => `${n} コース`,
    },
    course: {
      start: "コースを始める",
      glossary: "用語集",
      sources: "出典",
      ctaTitle: "自分のテーマで学びたい方へ",
      ctaBody: "Agent Mentor があなたのマシン上で、出典・練習・インタラクション付きのコースを生成します。",
      ctaButton: "Agent Mentor を見る ↗",
    },
    glossary: {
      breadcrumbSelf: "用語集",
      title: "用語集",
      subtitle: (n: number, courseTitle: string) => `『${courseTitle}』の用語 ${n} 件。レッスン本文で初出の箇所にホバーすると定義を確認できます。`,
      thTerm: "用語",
      thDef: "定義",
      thSource: "出典",
    },
    sources: { breadcrumbSelf: "出典" },
    card: {
      lessons: (n: number) => `${n} レッスン`,
      minutes: (n: number) => `約 ${n} 分`,
    },
    courseNav: { toc: "レッスン" },
    lessonNav: { prev: "前のレッスン", next: "次のレッスン" },
    copy: {
      code: "コードをコピー",
      copied: "コピーしました",
      failed: "コピーに失敗しました",
      link: "このセクションのリンクをコピー",
    },
  },
  blocks: {
    common: {
      check: "チェック",
      reset: "リセット",
      showFeedback: "フィードバックを見る",
      copyToAgent: "Agent にコピー",
      localCheckPassed: "ローカルチェックに合格しました。",
      localCheckFailed: "ローカルチェックに合格しませんでした。",
      loadingEditor: "エディターを読み込み中…",
    },
    exercise: {
      heading: "練習",
      title: (n: number, level: string) => `練習 ${n} · ${level}`,
      untitled: (n: number) => `練習 ${n}`,
      hint: (n: number) => `ヒント ${n}`,
      showAnswer: "模範解答を見る",
      rubric: "完了基準 · ローカルでチェック",
      agentCopy: { aria: "この練習を Agent にコピー", idle: "練習を Agent にコピー" },
    },
    mentorAction: {
      kicker: "Agent アクション",
      landmark: (label: string) => `Agent アクション：${label}`,
      copyAria: (label: string) => `Agent にコピー：${label}`,
    },
    order: {
      dragAria: (text: string) => `ドラッグして並べ替え：${text}`,
      moveUpAria: (text: string) => `上に移動：${text}`,
      moveDownAria: (text: string) => `下に移動：${text}`,
    },
    predict: { myPrediction: "自分の予測" },
    trace: {
      stepColumn: "ステップ",
      cellPassed: "合格",
      cellRetry: "再確認",
      allFilled: "入力可能なセルがすべて合格です。",
      partialFilled: (passed: number, total: number) => `入力可能なセル ${passed}/${total} が合格です。`,
    },
    code: {
      slotAria: (n: number) => `コードスロット ${n}`,
      bugLabel: "壊れている現象：",
      editorAria: "コード入力",
      allPassed: "ローカルチェックはすべて合格です。",
      partialPassed: (passed: number, total: number) => `ローカルチェック ${passed}/${total} が合格です。`,
    },
    diff: { choicesAria: "この変更の説明の選択肢" },
    sandbox: {
      preview: "プレビュー",
      restoreMine: "自分のコードを復元",
      showAnswer: "模範解答を見る",
      inspect: "検査",
      console: "コンソール",
      noMessages: "メッセージなし",
      clear: "クリア",
      replPlaceholder: "式を入力して Enter で実行",
      replAria: "コンソール入力",
      tabChangedAria: "模範解答がこのファイルを変更しました",
      closeErrorAria: "エラーメッセージを閉じる",
      mine: "自分の",
      answer: "解答",
      myCodePreviewTitle: "自分のコードのプレビュー",
      currentCodeLabel: "現在のコード：",
      emptyFile: "（空）",
      fileListSeparator: "、",
      statusRunning: "実行中…",
      statusErrors: (n: number) => `${n} 件のエラー`,
      statusAchieved: "目標達成",
      statusOk: "実行済み · エラーなし",
      editorAria: (tabLabel: string) => `${tabLabel} エディター`,
      toastAchieved: "目標達成。Agent にコピーして解法の議論を続けられます。",
      toastLoadedShared: "共有されたコードを読み込みました",
      toastRestoredAttempt: "前回の試行を復元しました。リセットで初期状態に戻ります",
      toastAppliedSolution: (files: string[]) => `模範解答を適用しました。変更先は ${files.join("、")} です。`,
      toastSolutionMatches: "模範解答は現在のコードと一致しています。",
      toastRestoredBeforeAnswer: "解答を表示する前のコードを復元しました。",
    },
  },
};

const ko: SiteCopy = {
  a11y: { breadcrumb: "탐색 경로" },
  header: { siteLink: "Agent Mentor 공식 사이트 ↗", switcher: "언어 변경" },
  drill: {
    glossaryMore: "용어를 Agent에 복사 →",
    deeper: "한 단계 더 깊이",
    liveBadge: "품질 검사 미통과",
    copied: "복사됨",
    copyFail: "복사 실패",
  },
  reader: {
    breadcrumbCourses: "코스",
    library: {
      title: "지금 일어나는 Agent 변화를, 바로 써먹는 강의로.",
      intro: "Agent와 직접 관련되고 아직도 빠르게 변화하는 주제만 다룹니다. 강의는 무료이며, 연습·코드·선택한 텍스트를 Claude Code, Codex 등의 Agent에 한 번에 복사해 이어갈 수 있습니다.",
      emptyTitle: "첫 번째 강의를 생성하는 중입니다",
      emptyBody: "출처, 인터랙션, Agent 관련성 검사를 통과한 강의만 여기에 표시됩니다.",
      ctaTitle: "내 목표에 맞는 강의를 Agent에게 만들게 하고 싶으신가요?",
      ctaBody: "Agent Mentor는 강의·연습·출처를 로컬에 저장해 당신의 Agent가 사용할 수 있게 합니다.",
      ctaButton: "Agent Mentor 알아보기 ↗",
      courseCount: (n: number) => `강의 ${n}개`,
    },
    course: {
      start: "강의 시작하기",
      glossary: "용어집",
      sources: "출처",
      ctaTitle: "내 주제로 배우고 싶으신가요?",
      ctaBody: "Agent Mentor가 당신의 컴퓨터에서 출처·연습·인터랙션이 포함된 강의를 생성합니다.",
      ctaButton: "Agent Mentor 알아보기 ↗",
    },
    glossary: {
      breadcrumbSelf: "용어집",
      title: "용어집",
      subtitle: (n: number, courseTitle: string) => `《${courseTitle}》의 용어 ${n}개. 레슨 본문에서 처음 등장하는 용어에 마우스를 올리면 정의를 볼 수 있습니다.`,
      thTerm: "용어",
      thDef: "정의",
      thSource: "출처",
    },
    sources: { breadcrumbSelf: "출처" },
    card: {
      lessons: (n: number) => `레슨 ${n}개`,
      minutes: (n: number) => `약 ${n}분`,
    },
    courseNav: { toc: "레슨" },
    lessonNav: { prev: "이전 레슨", next: "다음 레슨" },
    copy: {
      code: "코드 복사",
      copied: "복사됨",
      failed: "복사 실패",
      link: "이 섹션 링크 복사",
    },
  },
  blocks: {
    common: {
      check: "확인",
      reset: "초기화",
      showFeedback: "피드백 보기",
      copyToAgent: "Agent에 복사",
      localCheckPassed: "로컬 확인을 통과했습니다.",
      localCheckFailed: "로컬 확인을 통과하지 못했습니다.",
      loadingEditor: "편집기 로드 중…",
    },
    exercise: {
      heading: "연습",
      title: (n: number, level: string) => `연습 ${n} · ${level}`,
      untitled: (n: number) => `연습 ${n}`,
      hint: (n: number) => `힌트 ${n}`,
      showAnswer: "참고 답안 보기",
      rubric: "완료 기준 · 로컬에서 확인",
      agentCopy: { aria: "이 연습을 Agent에 복사", idle: "연습을 Agent에 복사" },
    },
    mentorAction: {
      kicker: "Agent 작업",
      landmark: (label: string) => `Agent 작업: ${label}`,
      copyAria: (label: string) => `Agent에 복사: ${label}`,
    },
    order: {
      dragAria: (text: string) => `드래그하여 순서 변경: ${text}`,
      moveUpAria: (text: string) => `위로 이동: ${text}`,
      moveDownAria: (text: string) => `아래로 이동: ${text}`,
    },
    predict: { myPrediction: "내 예측" },
    trace: {
      stepColumn: "단계",
      cellPassed: "통과",
      cellRetry: "다시 보기",
      allFilled: "입력 가능한 칸을 모두 통과했습니다.",
      partialFilled: (passed: number, total: number) => `입력 가능한 칸 ${passed}/${total}개를 통과했습니다.`,
    },
    code: {
      slotAria: (n: number) => `코드 슬롯 ${n}`,
      bugLabel: "깨진 현상:",
      editorAria: "코드 입력",
      allPassed: "로컬 확인을 모두 통과했습니다.",
      partialPassed: (passed: number, total: number) => `로컬 확인 ${passed}/${total}개를 통과했습니다.`,
    },
    diff: { choicesAria: "이 변경에 대한 설명 선택지" },
    sandbox: {
      preview: "미리 보기",
      restoreMine: "내 코드 복원",
      showAnswer: "참고 답안 보기",
      inspect: "검사",
      console: "콘솔",
      noMessages: "메시지 없음",
      clear: "지우기",
      replPlaceholder: "표현식을 입력하고 Enter를 눌러 실행",
      replAria: "콘솔 입력",
      tabChangedAria: "참고 답안이 이 파일을 변경했습니다",
      closeErrorAria: "오류 메시지 닫기",
      mine: "내 코드",
      answer: "답안",
      myCodePreviewTitle: "내 코드 미리 보기",
      currentCodeLabel: "현재 코드:",
      emptyFile: "(비어 있음)",
      fileListSeparator: ", ",
      statusRunning: "실행 중…",
      statusErrors: (n: number) => `오류 ${n}개`,
      statusAchieved: "목표 달성",
      statusOk: "실행됨 · 오류 없음",
      editorAria: (tabLabel: string) => `${tabLabel} 편집기`,
      toastAchieved: "목표 달성. Agent에 복사하여 풀이를 계속 논의할 수 있습니다.",
      toastLoadedShared: "공유된 코드를 불러왔습니다",
      toastRestoredAttempt: "지난 시도를 복원했습니다. 초기화하면 원래 상태로 돌아갑니다",
      toastAppliedSolution: (files: string[]) => `참고 답안을 적용했습니다. 변경 위치: ${files.join(", ")}.`,
      toastSolutionMatches: "참고 답안이 현재 코드와 일치합니다.",
      toastRestoredBeforeAnswer: "답안을 보기 전 코드로 복원했습니다.",
    },
  },
};

const es: SiteCopy = {
  a11y: { breadcrumb: "Navegación de migas de pan" },
  header: { siteLink: "Sitio de Agent Mentor ↗", switcher: "Cambiar idioma" },
  drill: {
    glossaryMore: "Copiar término al Agent →",
    deeper: "Un nivel más profundo",
    liveBadge: "sin verificación de calidad",
    copied: "Copiado",
    copyFail: "Error al copiar",
  },
  reader: {
    breadcrumbCourses: "Cursos",
    library: {
      title: "Los cambios del mundo Agent, convertidos en cursos prácticos.",
      intro: "Solo temas directamente relacionados con Agent y que aún cambian rápido. Los cursos son gratuitos: ejercicios, código y texto seleccionado se copian con un clic a Claude Code, Codex u otro Agent para continuar.",
      emptyTitle: "El primer curso se está generando",
      emptyBody: "Solo aparecen aquí los cursos que superan las comprobaciones de fuentes, interacción y relevancia para Agent.",
      ctaTitle: "¿Quieres que un Agent cree un curso para tu objetivo?",
      ctaBody: "Agent Mentor guarda cursos, ejercicios y fuentes en tu máquina, listos para tu propio Agent.",
      ctaButton: "Descubrir Agent Mentor ↗",
      courseCount: (n: number) => `${n} ${n === 1 ? "curso" : "cursos"}`,
    },
    course: {
      start: "Empezar el curso",
      glossary: "Glosario",
      sources: "Fuentes",
      ctaTitle: "¿Quieres un curso sobre tu propio tema?",
      ctaBody: "Agent Mentor genera cursos con fuentes, ejercicios e interacción en tu máquina.",
      ctaButton: "Descubrir Agent Mentor ↗",
    },
    glossary: {
      breadcrumbSelf: "Glosario",
      title: "Glosario",
      subtitle: (n: number, courseTitle: string) => `${n} ${n === 1 ? "término" : "términos"} de «${courseTitle}». Pasa el cursor sobre la primera aparición en la lección para ver la definición.`,
      thTerm: "Término",
      thDef: "Definición",
      thSource: "Fuente",
    },
    sources: { breadcrumbSelf: "Fuentes" },
    card: {
      lessons: (n: number) => `${n} ${n === 1 ? "lección" : "lecciones"}`,
      minutes: (n: number) => `~${n} min`,
    },
    courseNav: { toc: "Lecciones" },
    lessonNav: { prev: "Anterior", next: "Siguiente" },
    copy: {
      code: "Copiar código",
      copied: "Copiado",
      failed: "Error al copiar",
      link: "Copiar enlace de la sección",
    },
  },
  blocks: {
    common: {
      check: "Comprobar",
      reset: "Restablecer",
      showFeedback: "Ver comentarios",
      copyToAgent: "Copiar al Agent",
      localCheckPassed: "Comprobación local superada.",
      localCheckFailed: "Comprobación local no superada.",
      loadingEditor: "Cargando editor…",
    },
    exercise: {
      heading: "Ejercicios",
      title: (n: number, level: string) => `Ejercicio ${n} · ${level}`,
      untitled: (n: number) => `Ejercicio ${n}`,
      hint: (n: number) => `Pista ${n}`,
      showAnswer: "Ver respuesta de referencia",
      rubric: "Criterios de finalización · marcado local",
      agentCopy: { aria: "Copiar este ejercicio al Agent", idle: "Copiar ejercicio al Agent" },
    },
    mentorAction: {
      kicker: "Acción del Agent",
      landmark: (label: string) => `Acción del Agent: ${label}`,
      copyAria: (label: string) => `Copiar al Agent: ${label}`,
    },
    order: {
      dragAria: (text: string) => `Arrastrar para reordenar: ${text}`,
      moveUpAria: (text: string) => `Subir: ${text}`,
      moveDownAria: (text: string) => `Bajar: ${text}`,
    },
    predict: { myPrediction: "Mi predicción" },
    trace: {
      stepColumn: "Paso",
      cellPassed: "Superado",
      cellRetry: "Revisar",
      allFilled: "Todas las celdas rellenables superadas.",
      partialFilled: (passed: number, total: number) => `${passed}/${total} ${total === 1 ? "celda rellenable superada" : "celdas rellenables superadas"}.`,
    },
    code: {
      slotAria: (n: number) => `Espacio de código ${n}`,
      bugLabel: "Qué está roto:",
      editorAria: "Entrada de código",
      allPassed: "Comprobación local: todo superado.",
      partialPassed: (passed: number, total: number) => `Comprobación local: ${passed}/${total} superadas.`,
    },
    diff: { choicesAria: "Explicaciones de este cambio" },
    sandbox: {
      preview: "Vista previa",
      restoreMine: "Restaurar mi código",
      showAnswer: "Ver respuesta de referencia",
      inspect: "Inspeccionar",
      console: "Consola",
      noMessages: "Sin mensajes",
      clear: "Limpiar",
      replPlaceholder: "Escribe una expresión y pulsa Enter para ejecutar",
      replAria: "Entrada de consola",
      tabChangedAria: "La solución de referencia cambió este archivo",
      closeErrorAria: "Cerrar mensaje de error",
      mine: "Mío",
      answer: "Respuesta",
      myCodePreviewTitle: "Vista previa de mi código",
      currentCodeLabel: "Código actual:",
      emptyFile: "(vacío)",
      fileListSeparator: ", ",
      statusRunning: "Ejecutando…",
      statusErrors: (n: number) => `${n} ${n === 1 ? "error" : "errores"}`,
      statusAchieved: "Objetivo alcanzado",
      statusOk: "Ejecutado · sin errores",
      editorAria: (tabLabel: string) => `Editor de ${tabLabel}`,
      toastAchieved: "Objetivo alcanzado. Copia al Agent para seguir con tu solución.",
      toastLoadedShared: "Código compartido cargado",
      toastRestoredAttempt: "Se restauró tu último intento; restablecer vuelve al estado original",
      toastAppliedSolution: (files: string[]) => `Solución de referencia aplicada en ${files.join(", ")}.`,
      toastSolutionMatches: "La solución de referencia coincide con tu código actual.",
      toastRestoredBeforeAnswer: "Se restauró el código anterior a ver la respuesta.",
    },
  },
};

const ptBR: SiteCopy = {
  a11y: { breadcrumb: "Trilha de navegação" },
  header: { siteLink: "Site do Agent Mentor ↗", switcher: "Mudar idioma" },
  drill: {
    glossaryMore: "Copiar termo para o Agent →",
    deeper: "Um nível mais fundo",
    liveBadge: "sem verificação de qualidade",
    copied: "Copiado",
    copyFail: "Falha ao copiar",
  },
  reader: {
    breadcrumbCourses: "Cursos",
    library: {
      title: "As mudanças do ecossistema Agent, em cursos prontos para usar.",
      intro: "Só temas diretamente ligados a Agent e ainda em rápida mudança. Os cursos são gratuitos: exercícios, código e texto selecionado podem ser copiados com um clique para o Claude Code, Codex ou outro Agent continuar.",
      emptyTitle: "O primeiro curso está sendo gerado",
      emptyBody: "Somente cursos que passam pelas verificações de fontes, interação e relevância para Agent aparecem aqui.",
      ctaTitle: "Quer um Agent criando um curso para o seu objetivo?",
      ctaBody: "O Agent Mentor salva cursos, exercícios e fontes na sua máquina, prontos para o seu próprio Agent.",
      ctaButton: "Conhecer o Agent Mentor ↗",
      courseCount: (n: number) => `${n} ${n === 1 ? "curso" : "cursos"}`,
    },
    course: {
      start: "Começar o curso",
      glossary: "Glossário",
      sources: "Fontes",
      ctaTitle: "Quer aprender sobre seu próprio tema?",
      ctaBody: "O Agent Mentor gera cursos com fontes, exercícios e interação na sua máquina.",
      ctaButton: "Conhecer o Agent Mentor ↗",
    },
    glossary: {
      breadcrumbSelf: "Glossário",
      title: "Glossário",
      subtitle: (n: number, courseTitle: string) => `${n} ${n === 1 ? "termo" : "termos"} de “${courseTitle}”. Passe o cursor sobre a primeira ocorrência na lição para ver a definição.`,
      thTerm: "Termo",
      thDef: "Definição",
      thSource: "Fonte",
    },
    sources: { breadcrumbSelf: "Fontes" },
    card: {
      lessons: (n: number) => `${n} ${n === 1 ? "lição" : "lições"}`,
      minutes: (n: number) => `~${n} min`,
    },
    courseNav: { toc: "Lições" },
    lessonNav: { prev: "Anterior", next: "Próxima" },
    copy: {
      code: "Copiar código",
      copied: "Copiado",
      failed: "Falha ao copiar",
      link: "Copiar link da seção",
    },
  },
  blocks: {
    common: {
      check: "Verificar",
      reset: "Redefinir",
      showFeedback: "Ver feedback",
      copyToAgent: "Copiar para o Agent",
      localCheckPassed: "Verificação local aprovada.",
      localCheckFailed: "Verificação local não aprovada.",
      loadingEditor: "Carregando editor…",
    },
    exercise: {
      heading: "Exercícios",
      title: (n: number, level: string) => `Exercício ${n} · ${level}`,
      untitled: (n: number) => `Exercício ${n}`,
      hint: (n: number) => `Dica ${n}`,
      showAnswer: "Ver resposta de referência",
      rubric: "Critérios de conclusão · marcado localmente",
      agentCopy: { aria: "Copiar este exercício para o Agent", idle: "Copiar exercício para o Agent" },
    },
    mentorAction: {
      kicker: "Ação do Agent",
      landmark: (label: string) => `Ação do Agent: ${label}`,
      copyAria: (label: string) => `Copiar para o Agent: ${label}`,
    },
    order: {
      dragAria: (text: string) => `Arrastar para reordenar: ${text}`,
      moveUpAria: (text: string) => `Mover para cima: ${text}`,
      moveDownAria: (text: string) => `Mover para baixo: ${text}`,
    },
    predict: { myPrediction: "Minha previsão" },
    trace: {
      stepColumn: "Etapa",
      cellPassed: "Aprovado",
      cellRetry: "Rever",
      allFilled: "Todas as células preenchíveis aprovadas.",
      partialFilled: (passed: number, total: number) => `${passed}/${total} ${total === 1 ? "célula preenchível aprovada" : "células preenchíveis aprovadas"}.`,
    },
    code: {
      slotAria: (n: number) => `Espaço de código ${n}`,
      bugLabel: "O que está quebrado:",
      editorAria: "Entrada de código",
      allPassed: "Verificação local: tudo aprovado.",
      partialPassed: (passed: number, total: number) => `Verificação local: ${passed}/${total} aprovadas.`,
    },
    diff: { choicesAria: "Explicações para esta alteração" },
    sandbox: {
      preview: "Pré-visualização",
      restoreMine: "Restaurar meu código",
      showAnswer: "Ver resposta de referência",
      inspect: "Inspecionar",
      console: "Console",
      noMessages: "Sem mensagens",
      clear: "Limpar",
      replPlaceholder: "Digite uma expressão e pressione Enter para executar",
      replAria: "Entrada do console",
      tabChangedAria: "A solução de referência alterou este arquivo",
      closeErrorAria: "Fechar mensagem de erro",
      mine: "Meu",
      answer: "Resposta",
      myCodePreviewTitle: "Pré-visualização do meu código",
      currentCodeLabel: "Código atual:",
      emptyFile: "(vazio)",
      fileListSeparator: ", ",
      statusRunning: "Executando…",
      statusErrors: (n: number) => `${n} ${n === 1 ? "erro" : "erros"}`,
      statusAchieved: "Objetivo alcançado",
      statusOk: "Executado · sem erros",
      editorAria: (tabLabel: string) => `Editor de ${tabLabel}`,
      toastAchieved: "Objetivo alcançado. Copie para o Agent para continuar com sua solução.",
      toastLoadedShared: "Código compartilhado carregado",
      toastRestoredAttempt: "Sua última tentativa foi restaurada; redefinir volta ao estado original",
      toastAppliedSolution: (files: string[]) => `Solução de referência aplicada em ${files.join(", ")}.`,
      toastSolutionMatches: "A solução de referência corresponde ao seu código atual.",
      toastRestoredBeforeAnswer: "Código anterior à visualização da resposta restaurado.",
    },
  },
};

export const siteCopy: Record<Locale, SiteCopy> = {
  en,
  zh,
  ja,
  ko,
  es,
  "pt-BR": ptBR,
};
