export const siteCopy = {
  zh: {
    a11y: { breadcrumb: "面包屑导航" },
    drill: {
      glossaryMore: "复制术语给 Agent →",
      deeper: "再深一层",
      liveBadge: "未过质检",
      copied: "已复制",
      copyFail: "复制失败",
    },
    reader: {
      glossary: {
        breadcrumbLibrary: "课程",
        breadcrumbSelf: "术语表",
        title: "术语表",
        subtitle: (n: number, courseTitle: string) => `${n} 个术语，来自《${courseTitle}》。正文首次出现时可悬停查看释义。`,
        thTerm: "术语",
        thDef: "释义",
        thSource: "来源",
      },
      sources: { breadcrumbLibrary: "课程", breadcrumbSelf: "来源" },
      card: {
        lessons: (n: number) => `${n} 节`,
        minutes: (n: number) => `约 ${n} 分钟`,
      },
      courseNav: { toc: "课时" },
      lessonNav: { prev: "上一节", next: "下一节" },
      copy: {
        code: "复制代码",
        copied: "已复制",
        failed: "复制失败",
        link: "复制本节链接",
      },
    },
    blocks: {
      common: {
        check: "检查",
        reset: "重置",
        showFeedback: "查看反馈",
        copyToAgent: "复制给 Agent",
        localCheckPassed: "本地检查通过。",
        localCheckFailed: "本地检查未通过。",
        loadingEditor: "加载编辑器…",
      },
      exercise: {
        heading: "练习",
        title: (n: number, level: string) => `练习 ${n} · ${level}`,
        untitled: (n: number) => `练习 ${n}`,
        hint: (n: number) => `提示 ${n}`,
        showAnswer: "看参考答案",
        rubric: "完成标准 · 本地勾选",
        agentCopy: { aria: "复制这道练习给 Agent", idle: "复制练习给 Agent" },
      },
      mentorAction: {
        kicker: "Agent 动作",
        landmark: (label: string) => `Agent 动作：${label}`,
        copyAria: (label: string) => `复制给 Agent：${label}`,
      },
      order: {
        dragAria: (text: string) => `拖动排序：${text}`,
        moveUpAria: (text: string) => `上移：${text}`,
        moveDownAria: (text: string) => `下移：${text}`,
      },
      predict: { myPrediction: "我的预测" },
      trace: {
        stepColumn: "步骤",
        cellPassed: "通过",
        cellRetry: "再看",
        allFilled: "可填写格子全通过。",
        partialFilled: (passed: number, total: number) => `可填写格子 ${passed}/${total} 通过。`,
      },
      code: {
        slotAria: (n: number) => `代码空位 ${n}`,
        bugLabel: "坏掉的现象：",
        editorAria: "代码输入",
        allPassed: "本地检查全通过。",
        partialPassed: (passed: number, total: number) => `本地检查 ${passed}/${total} 通过。`,
      },
      diff: { choicesAria: "改动解释选项" },
      sandbox: {
        preview: "预览",
        restoreMine: "恢复我的代码",
        showAnswer: "看参考答案",
        inspect: "检查",
        console: "控制台",
        noMessages: "无消息",
        clear: "清空",
        replPlaceholder: "输入表达式，回车执行",
        replAria: "控制台输入",
        tabChangedAria: "参考答案改动了此段",
        closeErrorAria: "关闭错误提示",
        mine: "我的",
        answer: "答案",
        myCodePreviewTitle: "我的代码预览",
        currentCodeLabel: "当前代码：",
        emptyFile: "（空）",
        fileListSeparator: "、",
        statusRunning: "运行中…",
        statusErrors: (n: number) => `${n} 个错误`,
        statusAchieved: "目标达成",
        statusOk: "已运行 · 无错误",
        editorAria: (tabLabel: string) => `${tabLabel} 编辑器`,
        toastAchieved: "目标达成。可以复制给 Agent 继续讨论你的解法。",
        toastLoadedShared: "已加载分享的代码",
        toastRestoredAttempt: "已恢复你上次的尝试，重置可回到初始状态",
        toastAppliedSolution: (files: string[]) => `已应用参考答案，改动在 ${files.join("、")}。`,
        toastSolutionMatches: "参考答案与你的当前代码一致。",
        toastRestoredBeforeAnswer: "已恢复查看答案前的代码。",
      },
    },
  },
  en: {
    a11y: { breadcrumb: "Breadcrumb" },
    drill: {
      glossaryMore: "Copy term to Agent →",
      deeper: "One level deeper",
      liveBadge: "not course-checked",
      copied: "Copied",
      copyFail: "Copy failed",
    },
    reader: {
      glossary: {
        breadcrumbLibrary: "Courses",
        breadcrumbSelf: "Glossary",
        title: "Glossary",
        subtitle: (n: number, courseTitle: string) => `${n} ${n === 1 ? "term" : "terms"} from “${courseTitle}.” Hover the first occurrence in the lesson for its definition.`,
        thTerm: "Term",
        thDef: "Definition",
        thSource: "Source",
      },
      sources: { breadcrumbLibrary: "Courses", breadcrumbSelf: "Sources" },
      card: {
        lessons: (n: number) => `${n} ${n === 1 ? "lesson" : "lessons"}`,
        minutes: (n: number) => `~${n} min`,
      },
      courseNav: { toc: "Lessons" },
      lessonNav: { prev: "Previous", next: "Next" },
      copy: {
        code: "Copy code",
        copied: "Copied",
        failed: "Copy failed",
        link: "Copy section link",
      },
    },
    blocks: {
      common: {
        check: "Check",
        reset: "Reset",
        showFeedback: "Show feedback",
        copyToAgent: "Copy to Agent",
        localCheckPassed: "Local check passed.",
        localCheckFailed: "Local check failed.",
        loadingEditor: "Loading editor…",
      },
      exercise: {
        heading: "Exercises",
        title: (n: number, level: string) => `Exercise ${n} · ${level}`,
        untitled: (n: number) => `Exercise ${n}`,
        hint: (n: number) => `Hint ${n}`,
        showAnswer: "Show reference answer",
        rubric: "Done criteria · checked locally",
        agentCopy: { aria: "Copy this exercise to Agent", idle: "Copy exercise to Agent" },
      },
      mentorAction: {
        kicker: "Agent action",
        landmark: (label: string) => `Agent action: ${label}`,
        copyAria: (label: string) => `Copy to Agent: ${label}`,
      },
      order: {
        dragAria: (text: string) => `Drag to reorder: ${text}`,
        moveUpAria: (text: string) => `Move up: ${text}`,
        moveDownAria: (text: string) => `Move down: ${text}`,
      },
      predict: { myPrediction: "My prediction" },
      trace: {
        stepColumn: "Step",
        cellPassed: "Passed",
        cellRetry: "Retry",
        allFilled: "All fillable cells passed.",
        partialFilled: (passed: number, total: number) => `${passed}/${total} fillable ${total === 1 ? "cell" : "cells"} passed.`,
      },
      code: {
        slotAria: (n: number) => `Code slot ${n}`,
        bugLabel: "What's broken:",
        editorAria: "Code input",
        allPassed: "Local check: all passed.",
        partialPassed: (passed: number, total: number) => `Local check: ${passed}/${total} passed.`,
      },
      diff: { choicesAria: "Explanations for this change" },
      sandbox: {
        preview: "Preview",
        restoreMine: "Restore my code",
        showAnswer: "Show reference answer",
        inspect: "Inspect",
        console: "Console",
        noMessages: "No messages",
        clear: "Clear",
        replPlaceholder: "Type an expression, press Enter to run",
        replAria: "Console input",
        tabChangedAria: "The reference solution changed this file",
        closeErrorAria: "Close error message",
        mine: "Mine",
        answer: "Answer",
        myCodePreviewTitle: "My code preview",
        currentCodeLabel: "Current code:",
        emptyFile: "(empty)",
        fileListSeparator: ", ",
        statusRunning: "Running…",
        statusErrors: (n: number) => `${n} ${n === 1 ? "error" : "errors"}`,
        statusAchieved: "Goal reached",
        statusOk: "Ran · no errors",
        editorAria: (tabLabel: string) => `${tabLabel} editor`,
        toastAchieved: "Goal reached. Copy to Agent to continue with your solution.",
        toastLoadedShared: "Loaded shared code",
        toastRestoredAttempt: "Restored your last attempt; reset returns to the original",
        toastAppliedSolution: (files: string[]) => `Applied the reference solution in ${files.join(", ")}.`,
        toastSolutionMatches: "The reference solution matches your current code.",
        toastRestoredBeforeAnswer: "Restored the code from before you viewed the answer.",
      },
    },
  },
};

export type SiteCopy = (typeof siteCopy)["zh"];
